[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
chrono = "0.4"
tracing-subscriber = "0.2"
tracing = "0.1.40"
thiserror = "1.0.61"
anyhow = "1.0.86"
image = "0.25.1"
